### ISSUE TITLE
gdsii_arc 3 point option

### ISSUE THREAD

**Issue by ehud42** [ulfgri/gdsii-toolbox#2]
Is the code for the gdsii_arc using three points implemented yet?

I looked at the code and the help text is there, the calculation for the center is there but that is it.

**Comment by ulfgri** [comment]
Hi,

it looks like it should work. If you pass arc.x1, etc the function should use the coordinates to calculate the arc. Did you try it and it isn't working?

Ulf

On February 7, 2016 10:23:21 PM EST, ehud42 notifications@github.com wrote:

> Is the code for the gdsii_arc using three points implemented yet?
> 
> I looked at the code and the help text is there, the calculation for
> the center is there but that is it
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ulfgri/gdsii-toolbox/issues/2

## 

Ulf GRIESMANN
Somewhere on planet earth ...
Ph: +13013394962
