### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by dreens** [ulfgri/gdsii-toolbox#4]
A tutorial with example scripts is mentioned in the readme under documentation, but nowhere linked or stored. This seems like a wonderful repository, and I’d love to see a tutorial to get jumpstarted! Thanks for what seems like thorough and well done work.

**Comment by dreens** [comment]
I figured it out. I wasn't able to see the file because I had to click through a security warning that didn't show up unless I directly tried to click through to Ulf's google drive. Maybe it would be good to have one of these files directly in the repo? I can imagine there might be issues with this though.

**Comment by ulfgri** [comment]
Glad you found it

-- 
Ulf GRIESMANN   \\ +1 301 339 4962
Somewhere on Earth...
